---
- hosts: FreeBSD 
  gather_facts: false
  become: true
  vars:
    directory: /etc/ntp.conf #/etc/ntpsec/ntp.conf #/home/mari/ntp.conf 
    time_server: "{{ time_server }}"
    time_server_old: "{{ time_server_old }}"
  tasks:
    - name: Replace FreeBSD time server in file ntp.conf
      replace: 
        path: "{{ directory }}"
        regexp: "{{ time_server_old | regex_escape }}"
        replace: "{{ time_server }}"
      register: results

    - name: Show state message
      debug:
        msg: "{{ 'Time server changed succesfully!' if results.changed else 'Error changing time server' }}"

    - name: Restart ntp service
      ansible.builtin.service:
        name: ntpd
        # name: ntpsec 
        state: restarted