---
- hosts: OpenSuse
  gather_facts: false
  become: true
  vars:
    directory: /etc/chrony.conf # /etc/chrony/chrony.conf
    time_server: "{{ time_server }}"
    time_server_old: "{{ time_server_old }}"
  tasks:
    - name: Replace OpenSuse time server in file chrony.conf
      replace: 
        path: "{{ directory }}"
        regexp: "{{ time_server_old | regex_escape }}"
        replace: "{{ time_server }}"
      register: results

    - name: Show state message
      debug:
        msg: "{{ 'Time server changed succesfully!' if results.changed else 'Error changing time server' }}"

    - name: Restart chrony service
      ansible.builtin.service:
        name: chrony
        state: restarted